name: Build OpenWrt Docker x86-64 image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  FIRMWARE_URL: "https://github.com/xuncv/openwrt-builder/releases/download/2023.03.03-1849/openwrt-x86-64-generic-squashfs-rootfs.img.gz"
  REPOSITORY: mikelang/docker_openwrtx86-vn
  TAG: 23.11.05

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          TARGZFIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: TARGZFIRMWARE
          tags: "latest,${{ env.TAG }}"
